---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-deployment
  labels:
    app: hello-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: hello-nginx
          image: nginxdemos/hello
          ports:
            - containerPort: 80
              hostPort: 80
