---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Mi
  hostPath:
    path: /tmp/pv
    type: DirectoryOrCreate
